### ISSUE TITLE
Transformer implementation with local attention

### ISSUE THREAD

**Issue by serkansulun** [lucidrains/local-attention#10]
Hi, and thanks for the great work! I'm struggling to find an implementation of a complete transformer model (with multi-heads), that uses local attention, so that I can hopefully train with sequences of length 2048, using an 11 GB GTX 1080 Ti. Do you have any recommendations? Thanks in advance.

**Comment by lucidrains** [comment]
https://github.com/lucidrains/local-attention/blob/master/local_attention/transformer.py done
