### ISSUE TITLE
Which is exactly the attention pattern?

### ISSUE THREAD

**Issue by beleen23** [lucidrains/local-attention#11]
I'm struggling to know how does the attention pattern look. I understand it works in blocks, and you can choose how many blocks forward and backward you want to attend. However, it is not clear to me how is the shift between blocks done.
Is the pattern as in the picture below (for a window size of 3, look_forward=1, look_backward=1)?
![IMG_0069](https://user-images.githubusercontent.com/55488779/154454866-9d5fad19-a93d-4c00-ae64-22885d6f09a7.jpg)

Or is the shift just one token?

Thank you! :)

**Comment by guoweiyu** [comment]
I have the same question

**Comment by lucidrains** [comment]
yup, look forward and backwards is in multiple of the window size

your diagram is correct!

**Comment by gordicaleksa** [comment]
the README diagram confused me as well so for others & future me:
for look_forward=0, look_backward=1 the diagram looks exactly the same you just dissect it with the line of symmetry and you remove everything that's above.

EDIT: actually with `exact_windowsize` set to `True` we get the pattern in the README that's not chopped.
