### ISSUE TITLE
A bug of torch.arange for long sequence with fp16 data type

### ISSUE THREAD

**Issue by renll** [lucidrains/local-attention#12]
https://github.com/pytorch/pytorch/issues/81926

This line should use dtype=torch.long to support long sequence:
https://github.com/lucidrains/local-attention/blob/d30ad4a693ee32b0bc5a51fb79ae7634383a016e/local_attention/local_attention.py#L117

**Comment by lucidrains** [comment]
@renll thanks for identifying this bug!
