### ISSUE TITLE
xPos Rotary Embeddings

### ISSUE THREAD

**Issue by ilya16** [lucidrains/local-attention#14]
Hi! Two questions about Rotary Embedding with `use_xpos = True`:

1. What is the reason for setting `scale_base` to `window_size // 2`?

    I was testing an intermediate [SoundStream](https://github.com/lucidrains/audiolm-pytorch) checkpoint and it produced `nan` outputs for a test audio of >3 minutes (9000+ frames before encoder local attention). 

    The cause are abnormally large and infinite scales produced by `SinusoidalEmbeddings`. For `scale_base = 64`, the attention layer will fail for `seq_len > 9000`. With `fp16`, the point of failure point will be around `seq_len > 1150`.
    ```python
    import torch
    from local_attention.rotary import SinusoidalEmbeddings
    
    window_size = 128
    rel_pos = SinusoidalEmbeddings(64, scale_base= window_size // 2, use_xpos=True)
    q = torch.randn(8, 10000, 64)
    rel_pos(q)
    ```

2. Theoretical question:

    The rotary embeddings are applied before partitioning queries and keys into blocks:
    https://github.com/lucidrains/local-attention/blob/35ad6235530fc1aba6c9e8561d03ac18902c34a3/local_attention/local_attention.py#L111

    Would it be better to apply the embeddings "locally" after gathering all involved neighbouring blocks for each window?
    https://github.com/lucidrains/local-attention/blob/35ad6235530fc1aba6c9e8561d03ac18902c34a3/local_attention/local_attention.py#L141-L142
    The "global-relative" information will be lost, but I guess, we want to treat all local windows equally with respect to their neighbours, no matter if it is the first window, or something at thousands of time steps.

**Comment by lucidrains** [comment]
@ilya16 hey Ilya! wow, 3 minutes is already way more than i anticipated

i'll make it so the scale base can be overridden for your research, and i think i will also just build out dynamic positional bias, as it is better than trying to human engineer all this

**Comment by lucidrains** [comment]
@ilya16 also yes to your second question, i'll make the change 🙏 you are absolutely correct

**Comment by lucidrains** [comment]
@ilya16 ok, done, let me know if the latest version is good for you!

**Comment by ilya16** [comment]
@lucidrains thank you, looks good! 

I think 3 minutes with that many tokens is far from real-world applications, processing inputs in chunks is more feasible and closer to real-time use cases. And with the rotation after bucketing these overflow issues just go away.

I also think dynamic positional bias is a better choice, although I have not really tried it in x-transformers. I fancy ALiBi embeddings as they serve me well in my transformer model experiments.

**Comment by lucidrains** [comment]
@ilya16 yes ALiBi should be ok, but i'm a bit wary that some of the heads are too restricted locally in their attention (although would probably be a good fit here). also there is the failed Bloom model, which makes me wary of using any of its designs (ALiBi was used there)
