### ISSUE TITLE
question about the look around operation

### ISSUE THREAD

**Issue by benywon** [lucidrains/local-attention#2]
https://github.com/lucidrains/local-attention/blob/30ecd417d8eb095d3ef033d2641905349d893636/local_attention/local_attention.py#L45

Hey, I just find the local window attention implemented in Pytorch, thanks for your sharing! But I have a question about the 'look around' function, what is this function used for? can you explain it?

**Comment by lucidrains** [comment]
@benywon Hello! Yea! So basically look around tells you, for each window, gather `backward` windows into the past, and `forward` windows into the future. Each window will also always include itself. 

In the causal case, you will look around and gather then window 1 block into the past.

For non-causal, it will gather 1 window backwards and 1 window forwards

You can also set these receptive fields to whatever you wish

**Comment by benywon** [comment]
Thanks for your reply!!
