### ISSUE TITLE
Please add option for exact window_size masking

### ISSUE THREAD

**Issue by usamec** [lucidrains/local-attention#3]
```
        exact_mask = torch.abs(bq_t[:,:,:,None] - bq_k[:,:,None,:]) > self.window_size                                                                                              
        dots.masked_fill_(exact_mask, mask_value)                                                                     
```

This could be hidden under a flag similarly to shared_qk.

**Comment by lucidrains** [comment]
@usamec Hi Vlado, what is this trying to achieve? why are you subtracting the bucketed key values `bq_k` from the ticker values? `bq_t`

**Comment by lucidrains** [comment]
@usamec Hi Vlado! this is a great suggestion! building now

**Comment by lucidrains** [comment]
https://github.com/lucidrains/local-attention/releases/tag/1.2.0
